# Generated by Django 5.0.14 on 2025-10-06 20:19

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('organization_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('network', 'Healthcare Network'), ('private_practice', 'Private Practice')], help_text='Type of healthcare facility', max_length=50)),
                ('schema_name', models.CharField(db_index=True, help_text='PostgreSQL schema name for tenant isolation', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Schema name must start with a letter and contain only lowercase letters, numbers, and underscores', regex='^[a-z][a-z0-9_]*$')])),
                ('subdomain', models.CharField(db_index=True, help_text='Subdomain for URL routing (e.g., stmarys.otassess.com)', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must contain only lowercase letters, numbers, and hyphens', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')])),
                ('npi_number', models.CharField(blank=True, help_text='National Provider Identifier (10 digits)', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NPI number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('tax_id', models.CharField(blank=True, help_text='EIN/Tax ID', max_length=20, null=True)),
                ('business_associate_agreement_signed', models.BooleanField(default=False, help_text='Has the Business Associate Agreement been signed?')),
                ('baa_signed_date', models.DateField(blank=True, help_text='Date BAA was signed', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', help_text='Subscription tier', max_length=50)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users allowed')),
                ('max_patients', models.PositiveIntegerField(default=50, help_text='Maximum number of active patients allowed')),
                ('features_enabled', models.JSONField(blank=True, default=dict, help_text='Feature flags for this organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='organizatio_is_acti_cad598_idx'), models.Index(fields=['organization_type'], name='organizatio_organiz_650025_idx')],
            },
        ),
    ]
